### ISSUE TITLE
TXT2Tags didn't work in Python 3.7 and text written in UTF-8 encoding

### ISSUE THREAD

**Issue by dangmanhcuong87** [txt2tags/txt2tags#212] opened 2019-12-31 16:33 UTC
I tried converting a document written in UTF-8 encoding, and always get this error. Other English documents worked well. Using Windows 10 pro 64 bit, and the latest version of Python 3.7.
![Untitled](https://user-images.githubusercontent.com/40142033/71627527-8aa98900-2c25-11ea-945d-74a31c220295.png)

**Comment by aureliojargas** [comment] 2020-01-01 20:46
Hi @dangmanhcuong87, 

In a quick test here, it worked as expected with UTF-8:

- OS X 10.13.6
- Python 3.7.3
- txt2tags 3.4

```console
$ (echo; echo áéíóú) > test.t2t

$ file test.t2t
test.t2t: UTF-8 Unicode text

$ txt2tags -t sgml -o - -i test.t2t 
<!doctype linuxdoc system>
<article>


<p>
áéíóú

<!-- sgml code generated by txt2tags 3.4 (http://txt2tags.org) -->
<!-- cmdline: txt2tags -t sgml -o - -i test.t2t -->
</article>
$
```

Maybe your test file is in another (non UTF-8) encoding? Could you attach here a minimal sample file that triggers the exceptions?

**Comment by dangmanhcuong87** [comment] 2020-01-02 08:56
Hello
This is one of the files I saw that error. The old version (2.6) convert those file well. I wrote a short test file with the header from this, and it worked well. Don't know why. By the way, I use Python 3.7.5. Will try on Python 3.7.3 later.
Thanks for your featback

[NVDA-VI.txt](https://github.com/txt2tags/txt2tags/files/4015312/NVDA-VI.txt)

**Comment by aureliojargas** [comment] 2020-01-03 00:24
Hi @dangmanhcuong87 

Thanks for the files! I've downloaded them and could convert both in txt2tags 3.4 with no errors:

```console
$ txt2tags -t html -i NVDA-VI.txt 
txt2tags wrote NVDA-VI.html
$ txt2tags -t html -i test.txt 
txt2tags wrote test.html
$
````

One thing I've noticed, is that the NVDA-VI.txt file has this [BOM thing](https://en.wikipedia.org/wiki/Byte_order_mark) on it.

```console
$ file *.txt
NVDA-VI.txt: UTF-8 Unicode (with BOM) text, with very long lines, with CRLF line terminators
test.txt:    UTF-8 Unicode text, with CRLF line terminators
$
```

Maybe that's the source of the problem on Windows? I've copy/pasted the text into a new file and it does not have this BOM mark anymore: [NVDA-VI-no-BOM.txt](https://github.com/txt2tags/txt2tags/files/4017813/NVDA-VI-no-BOM.txt). Could you please test it on your setup?

```console
$ file *.txt
NVDA-VI-no-BOM.txt: UTF-8 Unicode text, with very long lines, with CRLF line terminators
NVDA-VI.txt:        UTF-8 Unicode (with BOM) text, with very long lines, with CRLF line terminators
test.txt:           UTF-8 Unicode text, with CRLF line terminators
$
```

**Comment by dangmanhcuong87** [comment] 2020-01-03 14:58
Hello @aureliojargas
I still have same error with the file you gave. I atach a screen contains error here, but so sorry because I'm blind so I'm not sure I catched all the screen. I'm please to test this on windows, and thanks for all of your replying.
![Error screen](https://user-images.githubusercontent.com/40142033/71730169-1153a580-2e74-11ea-88c5-2a5475cf26b5.png)

**Comment by aureliojargas** [comment] 2020-01-04 16:31
Hi @dangmanhcuong87, 

I've managed to test your files in a Windows machine and I could reproduce the error.

The problem is that the default encoding when opening files is decided by `locale.getpreferredencoding()`, which on Windows usually is `cp1252`, not `UTF-8`. So in your case, Python tried to read your UTF-8 file as cp1252, raising the error. More info here: https://stackoverflow.com/q/31469707

As pointed in https://docs.python.org/3/library/locale.html#locale.getpreferredencoding, one quick fix is to call Python in the "UTF-8 mode", by using the command line option `-X utf8` or by setting the environment variable `PYTHONUTF8` to 1. Examples:

```console
$ python3 -X utf8 ./txt2tags.py -t html -i NVDA-VI.txt
txt2tags wrote NVDA-VI.html

$ PYTHONUTF8=1 ./txt2tags.py -t html -i NVDA-VI.txt
txt2tags wrote NVDA-VI.html
```

The permanent fix is txt2tags always use `encoding="utf-8"` when opening files for reading and writing. See https://github.com/txt2tags/txt2tags/pull/214/commits/6a30f8973b66153d58071b380e0ad71c1907c326 for the implementation, if you want to reproduce it localy. But unfortunately this does not work in Python 2. We will work to find a solution for both and I'll post the PR link here.

Thanks again for the report!

**Comment by dangmanhcuong87** [comment] 2020-01-04 19:44
Hello @aureliojargas
I've successfully convert the file using two way you suggested. Thanks for your work on this. Will continue report error if any.
Cuong

**Comment by aureliojargas** [comment] 2020-01-11 08:35
Hi @dangmanhcuong87 

The pull request #221 was merged. It implemented a fix for your issue. Now txt2tags always open files as UTF-8 and should be able to open and convert your `NVDA-VI.txt` file correctly on Windows, with no need for the `-X utf8` or `PYTHONUTF8=1` workarounds.

Please tell us if there's still a problem.

**Comment by dangmanhcuong87** [comment] 2020-01-11 11:35
Hello aureliojargas, and thanks for your work. I downloaded it. Will try later.

**Comment by dangmanhcuong87** [comment] 2020-01-14 11:23
Hi. The program works as expected. Again, thanks for your work.

**Comment by aureliojargas** [comment] 2020-01-14 22:00
@dangmanhcuong87 Thank you very much for the feedback, I'm glad it worked!

**Closed by aureliojargas** 2020-01-14 22:00 UTC
