### ISSUE TITLE
Multiline Beautifiers - environments

### ISSUE THREAD

**Issue by flamenco108** [txt2tags/txt2tags#202] opened 2015-12-19 11:32 UTC
I write to pull a feature request: Multiline Beautifiers as environments. As I see, Aurelio had [written about it before](https://github.com/txt2tags/txt2tags/wiki/MultilineBeautifiers) and pointed, that it's tricky. In my opinion, it's not so tricky as the lack of it.

I think the proposition of notation given by Aurelio is right and clear:

```
***
This is a bold paragraph.
Intuitive marks, ain't it?
***
```

And pointed out possible problems:

```
***
This is a bold paragraph.

///
Now an italic one.
Oh, and bold also,
since we didn't close it.

___
***
Underlined paragraph, anyone?
Bold was closed, but italic not.

///

---
Now I closed italic.
But opened a strike out paragraph.
And... underlined is still opened (I guess).
Hey, I'm lost.
```

are not so problematic as they seem. Just there should be emphasized, that this way we mark the environment the way LaTeX do it. So there are possible multienvironments such as:

```
***
///
___
To be or not to be
___
///
***
```

will be correctly interpreted

**_**To be or not to be****_,

but incorrect nesting of environments 

```
///
***
___
To be or not to be
___
///
***
```

will be misenterpreted, **_as it happens today, when one tries to sign eg. multiline emphasis**_

**Comment by farvardin** [comment] 2015-12-19 16:39
The problem is while it's certainly very useful, adding this to the core of txt2tags will certainly lead to many problems for existing txt2tags code and users. 
The other thing to bear in mind is it's very trivial to add such a syntax in your txt2tags document: just add this kind of lines:

%!preproc: '\{ \*\* \}'   'CONVERTboldBEGIN'
%!preproc: '\{\/\*\* \}'  'CONVERTboldEND'

%!postproc(tex): 'CONVERTboldBEGIN'    '\\begin{bfseries}'
%!postproc(tex): 'CONVERTboldEND'      '\\end{bfseries}'

%!postproc(xhtml): 'CONVERTboldBEGIN'    '<div class="bold"><b>'
%!postproc(xhtml): 'CONVERTboldEND'      '</b></div>'

and it will be active for both tex and xhtml.

To prevent existing stars to be misinterpreted as bold, I've added extra brackets around them, so it will work this way:

{ ** }
this part

will be all

in bold 
{/** }

All my extra syntax are following this pattern: bracket, 4 characters, bracket. This way I can remove them easily with a regex. And with 4 symbols, it's enough to express everything.

You can see this in action there, I have several other case with multiline, which are certainly as needed as bold, italic and underline, such as centering, increase and decrese font size, boxed area... :

https://bitbucket.org/farvardin/textallion/src/default/core/textallion.t2t?at=default&fileviewer=file-view-default

**Comment by flamenco108** [comment] 2015-12-20 11:05
Thank you for this (so quick) information. 

It seems that txt2tags becomes sort of personal framework, as it is so configurable by postproc/preproc. Perhaps it's very good and specific way of development. 

Best wishes!

**Comment by fgallaire** [comment] 2015-12-20 11:56
> It seems that txt2tags becomes sort of personal framework, as it is so configurable by
> postproc/preproc. Perhaps it's very good and specific way of development.

Not at all. postproc/preproc is a great feature, but @farvardin is the only one to see it as a development tool.

**Comment by fgallaire** [comment] 2015-12-20 12:09
@flamenco108 I think this could be linked to my formatting (line and) area thinking:
https://github.com/txt2tags/txt2tags/issues/199#issuecomment-131473523
```
```*
```

**Comment by fgallaire** [comment] 2015-12-20 12:12
@farvardin Please to understand that if you have to link to textallion in your answer, it's not the answer a txt2tags user is waiting for.

**Comment by farvardin** [comment] 2015-12-20 12:42
I'm still secretly hoping @fgallaire will start soon his own fork of txt2tags, then all his development dreams would come true, he could change the current name (which he's considering bad), the current behaviour (which is not user-friendly enough), and so on. 

It would be better for everyone.

**Comment by aureliojargas** [comment] 2020-01-14 22:27
Taking into account that:

- the problems of multiline beautifiers are described in the mentioned wiki page and we still don't have a solution for them
- the OP has closed this issue
- it was reopened and the only new information is a link to another issue

I'm closing this one.

**Closed by aureliojargas** 2020-01-14 22:28 UTC
